---
title: Koder Akademi
timezone: Asia/Shanghai
collections:
  articles:
    title: Articles
    output: true
  docs:
    title: Docs
    output: true
  languages:
    title: Languages
    output: true
  page:
    title: Page
    output: true
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: article
    license: true
    category: post
    aside:
      toc: true
    show_edit_on_github: true
    pageview: true
- scope:
    path: ''
    type: articles
  values:
    show_date: false
- scope:
    path: ''
    type: languages
  values:
    layout: article
- scope:
    path: _docs/en
  values:
    layout: article
    sidebar:
      nav: docs-en
    license: true
    aside:
      toc: true
    show_edit_on_github: true
    show_date: false
- scope:
    path: _docs/zh
  values:
    layout: article
    sidebar:
      nav: docs-zh
    license: true
    aside:
      toc: true
    lang: zh
    show_edit_on_github: true
    show_date: false
text_skin: default
highlight_theme: default
url: https://tianqi.name
baseurl: 
description: 'A super customizable Jekyll theme for personal site, team site, blog,
  project, documentation, etc.

'
lang: tr
author:
  type: organization
  name: TeXt
  url: 
  avatar: "/assets/apple-touch-icon.png"
  bio: 'TeXt is a super customizable Jekyll theme for personal site, team site, blog,
    project, documentation, etc. Similar to iOS 11 style, it has large and prominent
    titles, round buttons and cards.

'
  email: kitian616@outlook.com
  facebook: 
  twitter: kitian616
  googleplus: '101827554735084402671'
  weibo: 234695683
  douban: 
  linkedin: 
  github: kitian616/jekyll-TeXt-theme
  npm: 
  telegram: 
repository: kitian616/jekyll-TeXt-theme
repository_tree: master
paths:
  root: 
  home: 
  archive: 
  rss: 
excerpt_separator: "<!--more-->"
license: CC-BY-4.0
toc:
  selectors: 
mathjax: true
mathjax_autoNumber: true
mermaid: true
chart: true
paginate: 8
paginate_path: "/page:num"
sources: 
comments:
  provider: gitalk
  disqus:
    shortname: 
  gitalk:
    clientID: 143666b578a416f82175
    clientSecret: 1d1c0604a1a4bff9b59ab7f56724dc0e8b837775
    repository: gitalk-demo
    owner: kitian616
    admin:
    - kitian616
pageview:
  provider: leancloud
  leancloud:
    app_id: uAG3OhdcH8H4fxSqXLyBljA7-gzGzoHsz
    app_key: Mzf5m9skSwYVWVXhGiYMNyXs
    app_class: TeXtDemo
analytics:
  provider: google
  google:
    tracking_id: UA-71907556-1
    anonymize_ip: false
markdown: kramdown
highlighter: rouge
permalink: date
exclude:
- CHANGELOG.md
- HOW_TO_RELEASE.md
- Gemfile
- Gemfile.lock
- LICENSE
- README-*.md
- README.md
- gulpfile.js
- jekyll-text-theme.gemspec
- package-lock.json
- package.json
- "/node_modules"
- "/vendor"
- "/_posts"
- "/index.html"
collections_dir: docs
plugins:
- jekyll-feed
- jekyll-paginate
- jekyll-sitemap
- jekyll-github-metadata
- jemoji
data_dir: "/docs/_data"
