---
title: Your Site Title
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
defaults:
- scope:
    path: ''
    type: posts
  values:
    layout: article
    license: true
    aside:
      toc: true
    show_edit_on_github: true
    pageview: true
text_skin: default
highlight_theme: default
url: 
baseurl: 
description: 'Your Site Description

'
lang: 
author:
  type: 
  name: Your Name
  url: 
  avatar: 
  bio: I am an amazing person.
  email: 
  facebook: 
  twitter: 
  googleplus: 
  weibo: 
  douban: 
  linkedin: 
  github: 
  npm: 
  telegram: 
repository: user_name/repo_name
repository_tree: master
paths:
  root: 
  home: 
  archive: 
  rss: 
excerpt_separator: "<!--more-->"
license: CC-BY-NC-4.0
toc:
  selectors: 
mathjax: 
mathjax_autoNumber: 
mermaid: 
chart: 
paginate: 8
paginate_path: "/page:num"
sources: 
comments:
  provider: false
  disqus:
    shortname: 
  gitalk:
    clientID: 
    clientSecret: 
    repository: 
    owner: 
    admin: 
pageview:
  provider: false
  leancloud:
    app_id: 
    app_key: 
    app_class: 
analytics:
  provider: false
  google:
    tracking_id: 
    anonymize_ip: false
markdown: kramdown
highlighter: rouge
permalink: date
exclude:
- CHANGELOG.md
- HOW_TO_RELEASE.md
- Gemfile
- Gemfile.lock
- LICENSE
- README-*.md
- README.md
- gulpfile.js
- jekyll-text-theme.gemspec
- package-lock.json
- package.json
- "/docs"
- "/node_modules"
- "/screenshots"
- "/test"
- "/vendor"
plugins:
- jekyll-feed
- jekyll-paginate
- jekyll-sitemap
- jemoji
