---
title: Title to this website
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
name: Website name
keywords: Key, words, about, this, website
<<<<<<< HEAD
baseurl: ""
url: /
=======
baseurl: ''
url: http://website.com
>>>>>>> 2683d5f8f0ffd788b03eb06e756d1df57197454c
description: Website description
cover: "/assets/img/cover.svg"
fanpage_id: ''
lang: en
lang_alternate: pt_BR
ssl: false
disqus: test
twitter: 
facebook: 
github: 
google: 
markdown: kramdown
permalink: "/:categories/:title/"
