slogan: "Endüstriyel Otomasyon Eğitimi ve Doküman Paylaşım Platformu"

theme: spacelab       # cerulean, cosmo, darkly, flatly, journal, lumen, paper
                  # readable, sandstone, simplex, slate, spacelab, superhero
                  # united, yeti
inverse: true

menu:

  - title: Anasayfa
    url:
    intro: "All the articles."
    icon: "fa fa-home"

#  - title: Arşiv
#    url: arsiv
#    intro: "All the articles."
#    icon: "fa fa-archive"

  - title: Kategoriler
    url: kategori
    intro: "All the categories."
    icon: "fa fa-folder"

  - title: Etiketler
    url: etiket
    intro: "All the tags."
    icon: "fa fa-tags"

  - title: Hakkında
    url: hakkinda
    intro: "About me."
    icon: "fa fa-user"
  
 # - commonweal: /404.html


links:
  - title: "Link1"
    url: https://link.com
    intro: "Açıklama."
    icon: "fa fa-facebook"
  - title: "Link2"
    url: https://link.com
    intro: "Açıklama."
    icon: "fa fa-facebook"
  - title: "Link3"
    url: https://link.com
    intro: "Açıklama."
    icon: "fa fa-facebook"

widgets:
- search
# - recent_comments # son yorumla sağ menüde gösterir.
# - category        # kategorileri sağ menüde gösterir.
# - tagcloud        # etiketleri sağ menüde gösterir.
- recent_posts
- links

rss:
fancybox: true
favicon: favicon.png
duoshuo_shortname: #freemindtheme

# Recommended posts
# Dependency: https://github.com/huiwang/hexo-recommended-posts
recommended_posts:
  enabled: false

# Analytics
google_analytics:
  enable: false
  siteid:
baidu_tongji:
  enable: false
  siteid:

# search
# swiftype_key: ZP2ZSuHgipSZfRyU8uTR

# share widgets
bdshare: true
jiathis: false

# built-in comment system
comment_js:
  type: ""
  user: ""
  repo: ""
  client_id: ""
  client_secret: "s"
  count: 5
